language: node_js
node_js:
  - "0.10"
notifications:
  email: false
deploy:
  provider: heroku
  app: heroku-deployment-badges
  strategy: git
  api_key:
    secure: ec15f026261a4c7063454074764257c4281eabe0
before_deploy:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi